--------------------------- MODULE Scenarios ---------------------------
EXTENDS TestSwitch
CONSTANTS Scenario, E1, E2, M1, M2, M3
VARIABLE pc
allvars == <<s,pc>>
Src(m,t) == [mac |-> m, tag |-> t]
D(a,b,c) == [i \in Slots |-> CASE i=1 -> a [] i=2 -> b [] OTHER -> c]
Present(v,m,p) == s.fdb[<<VlanToFdb[v],m>>].port=p
Absent(v,m) == s.fdb[<<VlanToFdb[v],m>>]=EmptyEntry
ScenarioInit == Init /\ pc=0
ScenarioLength == CASE Scenario="LiveEdit" -> 19
    [] Scenario="DeleteFallback" -> 24
    [] Scenario="SelectiveAndPvid" -> 21
    [] Scenario="StaleEdit" -> 12
    [] Scenario="AttachmentABA" -> 13
    [] Scenario="PortABA" -> 12
    [] Scenario="VlanABA" -> 16
    [] Scenario="Reboot" -> 11
    [] Scenario="SharedCache" -> 23
    [] Scenario="FaultAndDirect" -> 18
    [] Scenario="PauseManual" -> 13
    [] Scenario="DuplicateMacVlans" -> 13
    [] Scenario="DuplicateMacMove" -> 12
    [] Scenario="InstanceABA" -> 12
    [] Scenario="UnknownTag" -> 17
    [] Scenario="TrapOverflow" -> 5
    [] Scenario="TagLifecycle" -> 13
ScenarioNext ==
    \/ (pc=ScenarioLength /\ UNCHANGED allvars)
    \/ /\ Scenario="LiveEdit"
       /\ \/ (pc=0 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=1 /\ CreateVlan(20) /\ pc'=pc+1)
          \/ (pc=2 /\ ConfigurePort(1,10,{10,20}) /\ pc'=pc+1)
          \/ (pc=3 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=4 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=5 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=6 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=7 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=8 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=9 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=10 /\ EditEndpoint(E1,D(Src(M2,20),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=11 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=12 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=13 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=14 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=15 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=16 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=17 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=18 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="DeleteFallback"
       /\ \/ (pc=0 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=1 /\ CreateVlan(30) /\ pc'=pc+1)
          \/ (pc=2 /\ ConfigurePort(1,10,{10,30}) /\ pc'=pc+1)
          \/ (pc=3 /\ SetLegacy(10) /\ pc'=pc+1)
          \/ (pc=4 /\ CreateEndpoint(E1,D(Src(M1,Untagged),Src(M2,10),Src(M3,30))) /\ pc'=pc+1)
          \/ (pc=5 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=6 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=7 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=8 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=9 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ QueueActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=11 /\ ApplyActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=12 /\ QueueActivity(<<E1,3>>) /\ pc'=pc+1)
          \/ (pc=13 /\ ApplyActivity(<<E1,3>>) /\ pc'=pc+1)
          \/ (pc=14 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=15 /\ DeleteVlan(10) /\ pc'=pc+1)
          \/ (pc=16 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=17 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=18 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=19 /\ QueueActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=20 /\ ApplyActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=21 /\ QueueActivity(<<E1,3>>) /\ pc'=pc+1)
          \/ (pc=22 /\ ApplyActivity(<<E1,3>>) /\ pc'=pc+1)
          \/ (pc=23 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="SelectiveAndPvid"
       /\ \/ (pc=0 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=1 /\ CreateVlan(20) /\ pc'=pc+1)
          \/ (pc=2 /\ CreateVlan(30) /\ pc'=pc+1)
          \/ (pc=3 /\ ConfigurePort(1,10,{10,20,30}) /\ pc'=pc+1)
          \/ (pc=4 /\ CreateEndpoint(E1,D(Src(M1,Untagged),Src(M2,30),NoSource)) /\ pc'=pc+1)
          \/ (pc=5 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=6 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=7 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=8 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=9 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ QueueActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=11 /\ ApplyActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=12 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=13 /\ ConfigurePort(1,20,{10,20,30}) /\ pc'=pc+1)
          \/ (pc=14 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=15 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=16 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=17 /\ QueueActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=18 /\ ApplyActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=19 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=20 /\ ConfigurePort(1,20,{10,20}) /\ pc'=pc+1)
    \/ /\ Scenario="StaleEdit"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=4 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=5 /\ EditEndpoint(E1,D(Src(M2,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=6 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=7 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=8 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=9 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="AttachmentABA"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=4 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=5 /\ Move(E1,2) /\ pc'=pc+1)
          \/ (pc=6 /\ Move(E1,1) /\ pc'=pc+1)
          \/ (pc=7 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=8 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=9 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=10 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=12 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="PortABA"
       /\ \/ (pc=0 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=1 /\ CreateVlan(20) /\ pc'=pc+1)
          \/ (pc=2 /\ ConfigurePort(1,10,{10,20}) /\ pc'=pc+1)
          \/ (pc=3 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=4 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=5 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=6 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=7 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=8 /\ ConfigurePort(1,20,{10,20}) /\ pc'=pc+1)
          \/ (pc=9 /\ ConfigurePort(1,10,{10,20}) /\ pc'=pc+1)
          \/ (pc=10 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="VlanABA"
       /\ \/ (pc=0 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=1 /\ ConfigurePort(1,10,{10}) /\ pc'=pc+1)
          \/ (pc=2 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=3 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=4 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=5 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=6 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=7 /\ DeleteVlan(10) /\ pc'=pc+1)
          \/ (pc=8 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=9 /\ ConfigurePort(1,10,{10}) /\ pc'=pc+1)
          \/ (pc=10 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=12 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=13 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=14 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=15 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="Reboot"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=4 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=5 /\ Reboot /\ pc'=pc+1)
          \/ (pc=6 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=7 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=8 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=9 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="SharedCache"
       /\ \/ (pc=0 /\ SetMode(1,"shared") /\ pc'=pc+1)
          \/ (pc=1 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=2 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=3 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=4 /\ CreateEndpoint(E2,D(Src(M2,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=5 /\ SetActive(E2,TRUE) /\ pc'=pc+1)
          \/ (pc=6 /\ Connect(E2,1) /\ pc'=pc+1)
          \/ (pc=7 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=8 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=9 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ QueueActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ ApplyActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=12 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=13 /\ Disconnect(E1) /\ pc'=pc+1)
          \/ (pc=14 /\ DeleteEndpoint(E1) /\ pc'=pc+1)
          \/ (pc=15 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=16 /\ QueueActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=17 /\ ApplyActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=18 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=19 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=20 /\ QueueActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=21 /\ ApplyActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=22 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="FaultAndDirect"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=4 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=5 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=6 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=7 /\ SetFault(1,TRUE) /\ pc'=pc+1)
          \/ (pc=8 /\ Disconnect(E1) /\ pc'=pc+1)
          \/ (pc=9 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=10 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=12 /\ SetFault(1,FALSE) /\ pc'=pc+1)
          \/ (pc=13 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=14 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=15 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=16 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=17 /\ Disconnect(E1) /\ pc'=pc+1)
    \/ /\ Scenario="PauseManual"
       /\ \/ (pc=0 /\ SetPaused(TRUE) /\ pc'=pc+1)
          \/ (pc=1 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=2 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=3 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=4 /\ ManualTick /\ pc'=pc+1)
          \/ (pc=5 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=6 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=7 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=8 /\ SetActive(E1,FALSE) /\ pc'=pc+1)
          \/ (pc=9 /\ ManualTick /\ pc'=pc+1)
          \/ (pc=10 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=11 /\ ManualTick /\ pc'=pc+1)
          \/ (pc=12 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="DuplicateMacVlans"
       /\ \/ (pc=0 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=1 /\ CreateVlan(20) /\ pc'=pc+1)
          \/ (pc=2 /\ ConfigurePort(1,10,{10,20}) /\ pc'=pc+1)
          \/ (pc=3 /\ CreateEndpoint(E1,D(Src(M1,10),Src(M1,20),NoSource)) /\ pc'=pc+1)
          \/ (pc=4 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=5 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=6 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=7 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=8 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=9 /\ QueueActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=10 /\ ApplyActivity(<<E1,2>>) /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=12 /\ SetLegacy(10) /\ pc'=pc+1)
    \/ /\ Scenario="DuplicateMacMove"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ CreateEndpoint(E2,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=4 /\ SetActive(E2,TRUE) /\ pc'=pc+1)
          \/ (pc=5 /\ Connect(E2,2) /\ pc'=pc+1)
          \/ (pc=6 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=7 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=8 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=9 /\ QueueActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ ApplyActivity(<<E2,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="InstanceABA"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=4 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=5 /\ Disconnect(E1) /\ pc'=pc+1)
          \/ (pc=6 /\ DeleteEndpoint(E1) /\ pc'=pc+1)
          \/ (pc=7 /\ CreateEndpoint(E1,D(Src(M1,Untagged),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=8 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=9 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=10 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="UnknownTag"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,30),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=4 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=5 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=6 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=7 /\ CreateVlan(30) /\ pc'=pc+1)
          \/ (pc=8 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=9 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=11 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=12 /\ ConfigurePort(1,1,{1,30}) /\ pc'=pc+1)
          \/ (pc=13 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=14 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=15 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=16 /\ FinishStep /\ pc'=pc+1)
    \/ /\ Scenario="TrapOverflow"
       /\ \/ (pc=0 /\ SetMode(1,"shared") /\ pc'=pc+1)
          \/ (pc=1 /\ SetPartner(1,FALSE) /\ pc'=pc+1)
          \/ (pc=2 /\ SetPartner(1,TRUE) /\ pc'=pc+1)
          \/ (pc=3 /\ DispatchTrap /\ pc'=pc+1)
          \/ (pc=4 /\ Reboot /\ pc'=pc+1)
    \/ /\ Scenario="TagLifecycle"
       /\ \/ (pc=0 /\ CreateEndpoint(E1,D(Src(M1,10),NoSource,NoSource)) /\ pc'=pc+1)
          \/ (pc=1 /\ SetActive(E1,TRUE) /\ pc'=pc+1)
          \/ (pc=2 /\ Connect(E1,1) /\ pc'=pc+1)
          \/ (pc=3 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=4 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=5 /\ CreateVlan(10) /\ pc'=pc+1)
          \/ (pc=6 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=7 /\ FinishStep /\ pc'=pc+1)
          \/ (pc=8 /\ AutoTick /\ pc'=pc+1)
          \/ (pc=9 /\ QueueActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=10 /\ DeleteVlan(10) /\ pc'=pc+1)
          \/ (pc=11 /\ ApplyActivity(<<E1,1>>) /\ pc'=pc+1)
          \/ (pc=12 /\ FinishStep /\ pc'=pc+1)
ScenarioAssertions ==
    /\ pc \in 0..ScenarioLength
    /\ (Scenario="LiveEdit" /\ pc=10) => (Present(10,M1,1))
    /\ (Scenario="LiveEdit" /\ pc=11) => (Present(10,M1,1) /\ Len(s.traps)=1)
    /\ (Scenario="LiveEdit" /\ pc=15) => (Present(10,M1,1) /\ Present(20,M2,1) /\ Len(s.traps)=1)
    /\ (Scenario="LiveEdit" /\ pc=19) => (Absent(10,M1) /\ Present(20,M2,1))
    /\ (Scenario="DeleteFallback" /\ pc=16) => (s.pvid[1]=1 /\ s.allowed[1]={1,30} /\ s.legacy=1 /\ Absent(10,M1) /\ Absent(10,M2) /\ Present(30,M3,1) /\ s.fdb[<<VlanToFdb[30],M3>>].ttl=AgingTicks /\ s.sources[<<E1,2>>].tag=10 /\ Len(s.traps)=1)
    /\ (Scenario="DeleteFallback" /\ pc=24) => (Present(1,M1,1) /\ Absent(1,M2) /\ Absent(10,M2) /\ Present(30,M3,1))
    /\ (Scenario="DeleteFallback" /\ pc=24) => (~ENABLED DeleteVlan(1))
    /\ (Scenario="SelectiveAndPvid" /\ pc=14) => (Present(10,M1,1) /\ Present(30,M2,1) /\ s.fdb[<<VlanToFdb[10],M1>>].ttl=AgingTicks)
    /\ (Scenario="SelectiveAndPvid" /\ pc=20) => (Present(10,M1,1) /\ Present(20,M1,1))
    /\ (Scenario="SelectiveAndPvid" /\ pc=21) => (Present(10,M1,1) /\ Present(20,M1,1) /\ Absent(30,M2) /\ Len(s.traps)=1)
    /\ (Scenario="StaleEdit" /\ pc=7) => (Live(s)={})
    /\ (Scenario="StaleEdit" /\ pc=12) => (Absent(1,M1) /\ Present(1,M2,1))
    /\ (Scenario="AttachmentABA" /\ pc=8) => (Live(s)={})
    /\ (Scenario="AttachmentABA" /\ pc=13) => (Present(1,M1,1))
    /\ (Scenario="PortABA" /\ pc=11) => (Live(s)={})
    /\ (Scenario="VlanABA" /\ pc=11) => (Live(s)={})
    /\ (Scenario="VlanABA" /\ pc=16) => (Present(10,M1,1))
    /\ (Scenario="Reboot" /\ pc=6) => (s.attached[E1]=1 /\ E1 \in s.exists /\ E1 \in s.active /\ Live(s)={})
    /\ (Scenario="Reboot" /\ pc=8) => (Live(s)={})
    /\ (Scenario="Reboot" /\ pc=11) => (Present(1,M1,1))
    /\ (Scenario="SharedCache" /\ pc=14) => (Oper(s,1) /\ Present(1,M1,1) /\ Len(s.traps)=1)
    /\ (Scenario="SharedCache" /\ pc=15) => (Present(1,M1,1) /\ Oper(s,1))
    /\ (Scenario="SharedCache" /\ pc=23) => (Absent(1,M1) /\ Present(1,M2,1) /\ Oper(s,1) /\ Len(s.traps)=1)
    /\ (Scenario="FaultAndDirect" /\ pc=7) => (~ENABLED DeleteEndpoint(E1))
    /\ (Scenario="FaultAndDirect" /\ pc=8) => (Live(s)={} /\ s.attached[E1]=1)
    /\ (Scenario="FaultAndDirect" /\ pc=10) => (~Oper(s,1) /\ s.fault[1])
    /\ (Scenario="FaultAndDirect" /\ pc=12) => (Live(s)={})
    /\ (Scenario="FaultAndDirect" /\ pc=18) => (~Oper(s,1) /\ Live(s)={})
    /\ (Scenario="PauseManual" /\ pc=4) => (~ENABLED AutoTick /\ Live(s)={})
    /\ (Scenario="PauseManual" /\ pc=8) => (Present(1,M1,1) /\ s.paused /\ ~ENABLED AutoTick)
    /\ (Scenario="PauseManual" /\ pc=11) => (Present(1,M1,1))
    /\ (Scenario="PauseManual" /\ pc=13) => (Live(s)={})
    /\ (Scenario="DuplicateMacVlans" /\ pc=13) => (Cardinality(Live(s))=2 /\ DOMAIN Dot1dTpFdbTable={M1} /\ Dot1dBasePortTable[Dot1qTpFdbTable[<<VlanToFdb[10],M1>>].dot1qTpFdbPort].dot1dBasePortIfIndex=101)
    /\ (Scenario="DuplicateMacMove" /\ pc=12) => (Cardinality(Live(s))=1 /\ Present(1,M1,2))
    /\ (Scenario="InstanceABA" /\ pc=11) => (Live(s)={})
    /\ (Scenario="UnknownTag" /\ pc=7) => (Live(s)={} /\ s.sources[<<E1,1>>].tag=30)
    /\ (Scenario="UnknownTag" /\ pc=12) => (Live(s)={})
    /\ (Scenario="UnknownTag" /\ pc=17) => (Present(30,M1,1) /\ Len(s.traps)=1)
    /\ (Scenario="TrapOverflow" /\ pc=2) => (s.overflow /\ Len(s.traps)=1 /\ s.traps[1].kind="linkUp")
    /\ (Scenario="TrapOverflow" /\ pc=4) => (s.traps = <<>> /\ s.overflow)
    /\ (Scenario="TrapOverflow" /\ pc=5) => (~s.overflow)
    /\ (Scenario="TagLifecycle" /\ pc=6) => (~ValidJob(s,<<E1,1>>,s.pending[<<E1,1>>]))
    /\ (Scenario="TagLifecycle" /\ pc=7) => (Live(s)={})
    /\ (Scenario="TagLifecycle" /\ pc=11) => (~ValidJob(s,<<E1,1>>,s.pending[<<E1,1>>]))
    /\ (Scenario="TagLifecycle" /\ pc=12) => (Live(s)={})
ScenarioSpec == ScenarioInit /\ [][ScenarioNext]_allvars /\ WF_allvars(ScenarioNext)
Completes == <>(pc=ScenarioLength)
=============================================================================
