-------------------------- MODULE SetScenarios --------------------------
EXTENDS SetTransactions
CONSTANT Scenario
VARIABLE pc
scenarioVars == <<allvars,pc>>
ScenarioInit == TransactionInit /\ secret = [c \in Credentials |-> K1] /\ pc = 0
ScenarioLength == CASE Scenario="AtomicMixed" -> 27
    [] Scenario="RowStatus" -> 45
    [] Scenario="VlanFallback" -> 21
    [] Scenario="Authorization" -> 56
    [] Scenario="BitmapPorts" -> 13
    [] Scenario="AbsentDestroy" -> 8
    [] Scenario="IndependentViews" -> 24
ScenarioNext ==
    \/ (pc = ScenarioLength /\ UNCHANGED scenarioVars)
    \/ /\ Scenario = "AtomicMixed"
       /\ \/ (pc = 0 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 1 /\ (CoreAction(AutoTick)) /\ pc' = pc + 1)
          \/ (pc = 2 /\ (CoreAction(QueueActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 3 /\ (CoreAction(ApplyActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 4 /\ (CoreAction(FinishStep)) /\ pc' = pc + 1)
          \/ (pc = 5 /\ (SubmitSet(C1,K1,<<Op("row",10,4),Op("egress",10,{1}),Op("pvid",1,10)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 6 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 7 /\ (SubmitSet(C1,K1,<<Op("untagged",10,{1}),Op("untagged",1,{})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 8 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 9 /\ (SubmitSet(C1,K1,<<Op("pvid",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 10 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 11 /\ (SubmitSet(C1,K1,<<Op("admin",1,2),BadOp("name",10,1,"wrongLength")>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 12 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 13 /\ (SubmitSet(C1,K1,<<Op("admin",1,1),Op("pvid",1,10)>>,TRUE,FALSE)) /\ pc' = pc + 1)
          \/ (pc = 14 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 15 /\ (SubmitSet(C1,K1,<<Op("admin",1,2),Op("egress",10,{}),Op("untagged",10,{})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 16 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 17 /\ (SubmitSet(C1,K1,<<Op("admin",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 18 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 19 /\ (CoreAction(AutoTick)) /\ pc' = pc + 1)
          \/ (pc = 20 /\ (CoreAction(QueueActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 21 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 22 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 23 /\ (SubmitSet(C1,K1,<<Op("admin",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 24 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 25 /\ (CoreAction(ApplyActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 26 /\ (CoreAction(FinishStep)) /\ pc' = pc + 1)
    \/ /\ Scenario = "RowStatus"
       /\ \/ (pc = 0 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 1 /\ (SubmitSet(C1,K1,<<Op("name",10,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 2 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 3 /\ (SubmitSet(C1,K1,<<Op("row",10,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 4 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 5 /\ (SubmitSet(C1,K1,<<Op("row",10,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 6 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 7 /\ (SubmitSet(C1,K1,<<Op("row",10,5)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 8 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 9 /\ (SubmitSet(C1,K1,<<Op("row",10,3)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 10 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 11 /\ (SubmitSet(C1,K1,<<Op("row",10,6)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 12 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 13 /\ (SubmitSet(C1,K1,<<Op("row",10,4)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 14 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 15 /\ (SubmitSet(C1,K1,<<Op("egress",10,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 16 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 17 /\ (SubmitSet(C1,K1,<<Op("pvid",1,10),Op("forbidden",1,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 18 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 19 /\ (SubmitSet(C1,K1,<<Op("row",1,1),Op("forbidden",1,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 20 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 21 /\ (SubmitSet(C1,K1,<<Op("row",10,4)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 22 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 23 /\ (SubmitSet(C1,K1,<<Op("row",10,5)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 24 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 25 /\ (SubmitSet(C1,K1,<<Op("row",10,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 26 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 27 /\ (SubmitSet(C1,K1,<<Op("row",10,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 28 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 29 /\ (SubmitSet(C1,K1,<<Op("name",10,1),Op("name",10,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 30 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 31 /\ (SubmitSet(C1,K1,<<Op("name",10,0),Op("name",10,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 32 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 33 /\ (SubmitSet(C1,K1,<<Op("admin",1,1),Op("readonly",1,0)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 34 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 35 /\ (SubmitSet(C1,K1,<<Op("admin",1,1),BadOp("admin",1,2,"wrongType"),BadOp("name",10,0,"wrongLength")>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 36 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 37 /\ (SubmitSet(C1,K1,<<Op("admin",1,1),Op("forbidden",1,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 38 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 39 /\ (SubmitSet(C1,K1,<<Op("admin",1,3)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 40 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 41 /\ (SubmitSet(C1,K1,<<Op("row",1,6)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 42 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 43 /\ (SubmitSet(C1,K1,<<Op("row",10,6)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 44 /\ (HandleSet) /\ pc' = pc + 1)
    \/ /\ Scenario = "VlanFallback"
       /\ \/ (pc = 0 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 1 /\ (SubmitSet(C1,K1,<<Op("row",10,4),Op("egress",10,{1}),Op("pvid",1,10)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 2 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 3 /\ (SubmitSet(C1,K1,<<Op("untagged",10,{1}),Op("untagged",1,{})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 4 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 5 /\ (SubmitSet(C1,K1,<<Op("egress",1,{}),Op("forbidden",1,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 6 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 7 /\ (SubmitSet(C1,K1,<<Op("row",10,6)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 8 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 9 /\ (SubmitSet(C1,K1,<<Op("row",10,6),Op("row",20,4),Op("pvid",1,20),Op("egress",20,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 10 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 11 /\ (SubmitSet(C1,K1,<<Op("forbidden",1,{}),Op("untagged",20,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 12 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 13 /\ (SubmitSet(C1,K1,<<Op("row",20,6)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 14 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 15 /\ (SubmitSet(C1,K1,<<Op("row",10,4),Op("egress",10,{1}),Op("untagged",10,{1})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 16 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 17 /\ (CoreAction(ConfigurePort(1,10,{1,10}))) /\ pc' = pc + 1)
          \/ (pc = 18 /\ (SubmitSet(C1,K1,<<Op("untagged",10,{})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 19 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 20 /\ (CoreAction(ConfigurePort(1,1,{1,10}))) /\ pc' = pc + 1)
    \/ /\ Scenario = "Authorization"
       /\ \/ (pc = 0 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 1 /\ (SubmitSet(C2,K1,<<Op("admin",1,2)>>,FALSE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 2 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 3 /\ (SubmitSet(C2,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 4 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 5 /\ (SubmitSet(C1,K1,<<>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 6 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 7 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 8 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 9 /\ (Rotate(C1,K1)) /\ pc' = pc + 1)
          \/ (pc = 10 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 11 /\ (SubmitSet(C1,K1,<<Op("admin",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 12 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 13 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,FALSE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 14 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 15 /\ (Grant(C1,TRUE,{PortView})) /\ pc' = pc + 1)
          \/ (pc = 16 /\ (SubmitSet(C1,K1,<<Op("name",1,1)>>,FALSE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 17 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 18 /\ (SubmitSet(C1,K1,<<Op("admin",1,1),Op("name",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 19 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 20 /\ (Grant(C1,TRUE,Views)) /\ pc' = pc + 1)
          \/ (pc = 21 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 22 /\ (SetWriting(C1,FALSE)) /\ pc' = pc + 1)
          \/ (pc = 23 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 24 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 25 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 26 /\ (Rotate(C1,K2)) /\ pc' = pc + 1)
          \/ (pc = 27 /\ (Rotate(C1,K1)) /\ pc' = pc + 1)
          \/ (pc = 28 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 29 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 30 /\ (SetGate(FALSE)) /\ pc' = pc + 1)
          \/ (pc = 31 /\ (SetGate(TRUE)) /\ pc' = pc + 1)
          \/ (pc = 32 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 33 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 34 /\ (SetReboot) /\ pc' = pc + 1)
          \/ (pc = 35 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 36 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 37 /\ (SetReboot) /\ pc' = pc + 1)
          \/ (pc = 38 /\ (SetReboot) /\ pc' = pc + 1)
          \/ (pc = 39 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 40 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 41 /\ (RemoveCredential(C1)) /\ pc' = pc + 1)
          \/ (pc = 42 /\ (Rotate(C1,K1)) /\ pc' = pc + 1)
          \/ (pc = 43 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 44 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 45 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 46 /\ (Grant(C1,FALSE,Views)) /\ pc' = pc + 1)
          \/ (pc = 47 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 48 /\ (Grant(C1,TRUE,Views)) /\ pc' = pc + 1)
          \/ (pc = 49 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 50 /\ (Grant(C1,TRUE,{VlanView})) /\ pc' = pc + 1)
          \/ (pc = 51 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 52 /\ (Grant(C1,TRUE,Views)) /\ pc' = pc + 1)
          \/ (pc = 53 /\ (Access!SaveCredential(C1,TRUE,FALSE,viewOf[C1],K1) /\ UNCHANGED <<s,pending,result,registration,gate,activation>>) /\ pc' = pc + 1)
          \/ (pc = 54 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 55 /\ (HandleSet) /\ pc' = pc + 1)
    \/ /\ Scenario = "BitmapPorts"
       /\ \/ (pc = 0 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 1 /\ (SubmitSet(C1,K1,<<Op("row",10,4),Op("egress",10,{1,2}),Op("untagged",10,{1,2})>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 2 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 3 /\ (SubmitSet(C1,K1,<<Op("pvid",1,10),Op("pvid",2,10)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 4 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 5 /\ (CoreAction(AutoTick)) /\ pc' = pc + 1)
          \/ (pc = 6 /\ (CoreAction(QueueActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 7 /\ (CoreAction(ApplyActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 8 /\ (CoreAction(FinishStep)) /\ pc' = pc + 1)
          \/ (pc = 9 /\ (SubmitSet(C1,K1,<<Op("egress",10,{2}),Op("untagged",10,{2}),Op("pvid",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 10 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 11 /\ (SubmitSet(C1,K1,<<Op("admin",2,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 12 /\ (HandleSet) /\ pc' = pc + 1)
    \/ /\ Scenario = "AbsentDestroy"
       /\ \/ (pc = 0 /\ (SetWriting(C1,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 1 /\ (CoreAction(EditEndpoint(E0,OneDef(M0,10)))) /\ pc' = pc + 1)
          \/ (pc = 2 /\ (CoreAction(AutoTick)) /\ pc' = pc + 1)
          \/ (pc = 3 /\ (CoreAction(QueueActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 4 /\ (SubmitSet(C1,K1,<<Op("row",10,6),Op("admin",2,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 5 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 6 /\ (CoreAction(ApplyActivity(<<E0,1>>))) /\ pc' = pc + 1)
          \/ (pc = 7 /\ (CoreAction(FinishStep)) /\ pc' = pc + 1)
    \/ /\ Scenario = "IndependentViews"
       /\ \/ (pc = 0 /\ (ChangeView(viewOf[C1],{VlanView})) /\ pc' = pc + 1)
          \/ (pc = 1 /\ (ChangeView(viewOf[C2],{PortView})) /\ pc' = pc + 1)
          \/ (pc = 2 /\ (SetWriteView(C1,TRUE,viewOf[C2])) /\ pc' = pc + 1)
          \/ (pc = 3 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 4 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 5 /\ (SubmitSet(C1,K1,<<Op("admin",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 6 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 7 /\ (SetWriteView(C2,TRUE,viewOf[C2])) /\ pc' = pc + 1)
          \/ (pc = 8 /\ (SubmitSet(C2,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 9 /\ (ChangeView(viewOf[C2],{VlanView})) /\ pc' = pc + 1)
          \/ (pc = 10 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 11 /\ (ChangeView(viewOf[C2],{PortView})) /\ pc' = pc + 1)
          \/ (pc = 12 /\ (SubmitSet(C2,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 13 /\ (ChangeView(viewOf[C2],{VlanView})) /\ pc' = pc + 1)
          \/ (pc = 14 /\ (ChangeView(viewOf[C2],{PortView})) /\ pc' = pc + 1)
          \/ (pc = 15 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 16 /\ (SubmitSet(C2,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 17 /\ (ChangeView(viewOf[C2],{PortView})) /\ pc' = pc + 1)
          \/ (pc = 18 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 19 /\ (SubmitSet(C2,K1,<<Op("admin",1,1)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 20 /\ (HandleSet) /\ pc' = pc + 1)
          \/ (pc = 21 /\ (SubmitSet(C1,K1,<<Op("admin",1,2)>>,TRUE,TRUE)) /\ pc' = pc + 1)
          \/ (pc = 22 /\ (ChangeView(viewOf[C1],Views)) /\ pc' = pc + 1)
          \/ (pc = 23 /\ (HandleSet) /\ pc' = pc + 1)
ScenarioAssertions ==
    /\ pc \in 0..ScenarioLength
    /\ (Scenario = "AtomicMixed" /\ pc = 5 => (Live(s) # {}))
    /\ (Scenario = "AtomicMixed" /\ pc = 7 => (result.status = "noError" /\ result.index = 0 /\ s.pvid[1] = 10 /\ s.untagged[1] = {1} /\ Live(s) # {}))
    /\ (Scenario = "AtomicMixed" /\ pc = 9 => (result.status = "noError" /\ result.index = 0 /\ s.untagged[1] = {10}))
    /\ (Scenario = "AtomicMixed" /\ pc = 11 => (result.status = "noError" /\ result.index = 0 /\ s.pvid[1] = 1 /\ s.untagged[1] = {10}))
    /\ (Scenario = "AtomicMixed" /\ pc = 13 => (result.status = "wrongLength" /\ result.index = 2 /\ s.admin[1] /\ Live(s) # {}))
    /\ (Scenario = "AtomicMixed" /\ pc = 15 => (result.status = "commitFailed" /\ result.index = 2 /\ s.pvid[1] = 1 /\ s.admin[1] /\ Live(s) # {}))
    /\ (Scenario = "AtomicMixed" /\ pc = 17 => (result.status = "noError" /\ result.index = 0 /\ ~s.admin[1] /\ Live(s) = {} /\ s.allowed[1] = {1}))
    /\ (Scenario = "AtomicMixed" /\ pc = 19 => (result.status = "noError" /\ result.index = 0 /\ s.admin[1]))
    /\ (Scenario = "AtomicMixed" /\ pc = 23 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "AtomicMixed" /\ pc = 25 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "AtomicMixed" /\ pc = 26 => (Live(s) = {}))
    /\ (Scenario = "RowStatus" /\ pc = 3 => (result.status = "inconsistentName" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 5 => (result.status = "inconsistentValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 7 => (result.status = "inconsistentValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 9 => (result.status = "wrongValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 11 => (result.status = "wrongValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 13 => (result.status = "noError" /\ result.index = 0 /\ s.vlans = {1}))
    /\ (Scenario = "RowStatus" /\ pc = 15 => (result.status = "noError" /\ result.index = 0 /\ s.vlans = {1,10} /\ s.vlanNames[10] = 0 /\ s.allowed[1] = {1}))
    /\ (Scenario = "RowStatus" /\ pc = 17 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "RowStatus" /\ pc = 19 => (result.status = "inconsistentValue" /\ result.index = 2))
    /\ (Scenario = "RowStatus" /\ pc = 21 => (result.status = "inconsistentValue" /\ result.index = 2))
    /\ (Scenario = "RowStatus" /\ pc = 23 => (result.status = "inconsistentValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 25 => (result.status = "inconsistentValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 27 => (result.status = "wrongValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 29 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "RowStatus" /\ pc = 31 => (result.status = "noError" /\ result.index = 0 /\ s.vlanNames[10] = 1))
    /\ (Scenario = "RowStatus" /\ pc = 33 => (result.status = "inconsistentValue" /\ result.index = 2 /\ s.vlanNames[10] = 1))
    /\ (Scenario = "RowStatus" /\ pc = 35 => (result.status = "notWritable" /\ result.index = 2))
    /\ (Scenario = "RowStatus" /\ pc = 37 => (result.status = "wrongType" /\ result.index = 2))
    /\ (Scenario = "RowStatus" /\ pc = 39 => (result.status = "inconsistentValue" /\ result.index = 2))
    /\ (Scenario = "RowStatus" /\ pc = 41 => (result.status = "wrongValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 43 => (result.status = "inconsistentValue" /\ result.index = 1))
    /\ (Scenario = "RowStatus" /\ pc = 45 => (result.status = "noError" /\ result.index = 0 /\ s.vlans = {1}))
    /\ (Scenario = "VlanFallback" /\ pc = 3 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "VlanFallback" /\ pc = 5 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "VlanFallback" /\ pc = 7 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "VlanFallback" /\ pc = 9 => (result.status = "inconsistentValue" /\ result.index = 1 /\ s.vlans = {1,10} /\ s.pvid[1] = 10))
    /\ (Scenario = "VlanFallback" /\ pc = 11 => (result.status = "noError" /\ result.index = 0 /\ s.pvid[1] = 20 /\ s.allowed[1] = {20} /\ s.untagged[1] = {} /\ s.forbidden[1] = {1}))
    /\ (Scenario = "VlanFallback" /\ pc = 13 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "VlanFallback" /\ pc = 15 => (result.status = "noError" /\ result.index = 0 /\ s.pvid[1] = 1 /\ s.allowed[1] = {1} /\ s.untagged[1] = {1}))
    /\ (Scenario = "VlanFallback" /\ pc = 17 => (result.status = "noError" /\ result.index = 0 /\ s.untagged[1] = {1,10}))
    /\ (Scenario = "VlanFallback" /\ pc = 18 => (s.pvid[1] = 10 /\ s.untagged[1] = {10}))
    /\ (Scenario = "VlanFallback" /\ pc = 20 => (result.status = "noError" /\ result.index = 0 /\ s.untagged[1] = {}))
    /\ (Scenario = "VlanFallback" /\ pc = 21 => (s.pvid[1] = 1 /\ s.untagged[1] = {1}))
    /\ (Scenario = "Authorization" /\ pc = 3 => (result.status = "tooBig" /\ result.index = 0 /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 5 => (result.status = "authorizationError" /\ result.index = 0))
    /\ (Scenario = "Authorization" /\ pc = 7 => (result.status = "noError" /\ result.index = 0 /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 11 => (result.status = "noError" /\ ~s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 13 => (result.status = "noError" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 15 => (result.status = "tooBig" /\ result.index = 0))
    /\ (Scenario = "Authorization" /\ pc = 18 => (result.status = "tooBig" /\ result.index = 0 /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 20 => (result.status = "noAccess" /\ result.index = 2))
    /\ (Scenario = "Authorization" /\ pc = 25 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 29 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 33 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 36 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 40 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 45 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 48 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 52 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "Authorization" /\ pc = 54 => (C1 \notin polling /\ Access!WriteAuthorized(C1,K1)))
    /\ (Scenario = "Authorization" /\ pc = 56 => (result.status = "noError" /\ result.index = 0 /\ ~s.admin[1]))
    /\ (Scenario = "BitmapPorts" /\ pc = 3 => (result.status = "noError" /\ result.index = 0 /\ s.allowed[1] = {1,10} /\ s.allowed[2] = {1,10} /\ s.untagged[1] = {1,10}))
    /\ (Scenario = "BitmapPorts" /\ pc = 5 => (result.status = "noError" /\ result.index = 0 /\ s.untagged[1] = {1,10} /\ s.untagged[2] = {1,10}))
    /\ (Scenario = "BitmapPorts" /\ pc = 9 => (s.fdb[<<VlanToFdb[10],M0>>].port = 1))
    /\ (Scenario = "BitmapPorts" /\ pc = 11 => (result.status = "noError" /\ result.index = 0 /\ s.fdb[<<VlanToFdb[10],M0>>] = EmptyEntry /\ s.allowed[2] = {1,10} /\ s.pvid[2] = 10))
    /\ (Scenario = "BitmapPorts" /\ pc = 13 => (result.status = "noError" /\ result.index = 0 /\ ~Oper(s,2) /\ s.allowed[2] = {1,10}))
    /\ (Scenario = "AbsentDestroy" /\ pc = 4 => (ValidJob(s,<<E0,1>>,s.pending[<<E0,1>>])))
    /\ (Scenario = "AbsentDestroy" /\ pc = 6 => (result.status = "noError" /\ result.index = 0 /\ ValidJob(s,<<E0,1>>,s.pending[<<E0,1>>]) /\ ~s.admin[2]))
    /\ (Scenario = "AbsentDestroy" /\ pc = 7 => (Live(s) = {}))
    /\ (Scenario = "IndependentViews" /\ pc = 3 => (writeViewOf[C1] # viewOf[C1]))
    /\ (Scenario = "IndependentViews" /\ pc = 5 => (result.status = "noError" /\ result.index = 0 /\ ~s.admin[1] /\ Access!Reply([credential |-> C1,suppliedSecret |-> K1,requestedViews |-> {PortView}]).returnedViews = {}))
    /\ (Scenario = "IndependentViews" /\ pc = 7 => (result.status = "noError" /\ result.index = 0))
    /\ (Scenario = "IndependentViews" /\ pc = 11 => (result.status = "dropped" /\ result.index = 0 /\ s.admin[1]))
    /\ (Scenario = "IndependentViews" /\ pc = 16 => (result.status = "dropped" /\ s.admin[1]))
    /\ (Scenario = "IndependentViews" /\ pc = 19 => (result.status = "noError" /\ ~s.admin[1]))
    /\ (Scenario = "IndependentViews" /\ pc = 21 => (result.status = "noError" /\ s.admin[1]))
    /\ (Scenario = "IndependentViews" /\ pc = 24 => (result.status = "noError" /\ ~s.admin[1]))
ScenarioSpec == ScenarioInit /\ [][ScenarioNext]_scenarioVars /\ WF_scenarioVars(ScenarioNext)
Completes == <>(pc = ScenarioLength)
=============================================================================
