// Run against a fresh local instance. Requires Playwright and Chromium.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browserEnv={...process.env};
  if(process.env.SWITCHLAB_BROWSER_LIBRARY_PATH)browserEnv.LD_LIBRARY_PATH=process.env.SWITCHLAB_BROWSER_LIBRARY_PATH;
  if(process.env.SWITCHLAB_BROWSER_FONTCONFIG)browserEnv.FONTCONFIG_FILE=process.env.SWITCHLAB_BROWSER_FONTCONFIG;
  const browser = await chromium.launch({headless:true,channel:process.env.SWITCHLAB_BROWSER_CHANNEL||undefined,env:browserEnv});
  try {
  const page = await browser.newPage({viewport:{width:1440,height:1100}});
  page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const screenshots=process.env.SWITCHLAB_TEST_SCREENSHOTS||path.join(__dirname,'../docs/screenshots');fs.mkdirSync(screenshots,{recursive:true});
  const fixtureURL=process.env.SWITCHLAB_TEST_URL||'http://127.0.0.1:8765';
  const fixtureOrigin=new URL(fixtureURL).origin;
  await page.route('**/*',route=>new URL(route.request().url()).origin===fixtureOrigin?route.continue():route.abort());
  await page.goto(fixtureURL);
  assert.equal(await page.locator('[name=setup_token]').count(),0);
  assert.equal(await page.getByLabel('Administrator password').getAttribute('minlength'),null);
  assert.equal(await page.getByLabel('Administrator password').getAttribute('maxlength'),'1024');
  await page.getByLabel('Administrator password').fill(process.env.SWITCHLAB_TEST_PASSWORD);
  await page.getByRole('button',{name:'Create administrator'}).click();
  await page.getByRole('heading',{name:'Switch overview',exact:true}).waitFor();
  await page.getByRole('button',{name:'Ⅱ Pause',exact:true}).click();
  await page.getByRole('button',{name:'▶ Resume',exact:true}).waitFor();
  await page.screenshot({path:path.join(screenshots,'overview-empty.png'),fullPage:true});
  await page.locator('nav button[data-id=endpoints]').click();
  await page.getByRole('button',{name:'+ New endpoint',exact:true}).click();
  await page.getByLabel('Display name').fill('Lab workstation');
  await page.getByLabel('MAC address',{exact:true}).fill('02:11:22:33:44:55');
  await page.getByRole('button',{name:'Create endpoint',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Attach →',exact:true}).click();
  await page.getByRole('button',{name:'Connect endpoint',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'+1s',exact:true}).click();
  await page.locator('nav button[data-id=fdb]').click();
  await page.getByText('02:11:22:33:44:55',{exact:true}).waitFor();
  await page.screenshot({path:path.join(screenshots,'learned-addresses.png'),fullPage:true});
  await page.locator('nav button[data-id=overview]').click();
  await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('show'));
  await page.screenshot({path:path.join(screenshots,'overview.png'),fullPage:true});
  await page.getByRole('button',{name:'Configure port',exact:true}).click();
  await page.getByLabel('Alias',{exact:true}).fill('Edited through the browser');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('nav button[data-id=settings]').click();
  const state=()=>page.evaluate(async()=> (await fetch('/api/v1/state')).json());
  const credentialRow=label=>page.locator('.setting-row').filter({has:page.locator('b',{hasText:label})});
  async function saveCredential(version){
    const request=page.waitForRequest(r=>r.url().includes('/api/v1/snmp/credentials')&&['POST','PUT'].includes(r.method()));
    await page.getByRole('button',{name:'Save changes',exact:true}).click();
    const payload=(await request).postDataJSON();
    await page.locator('dialog').waitFor({state:'hidden'});
    assert.equal(payload.version,version);
    const inactive=version==='2c'?['username','security_level','auth_key','priv_key']:['community'];
    for(const key of inactive)assert.equal(key in payload,false,`Inactive field ${key} submitted`);
    const snapshot=await state();
    const credential=Object.values(snapshot.credentials).find(c=>c.label===payload.label);
    assert.ok(credential);
    for(const key of ['community','auth_key','priv_key'])assert.equal(key in credential,false);
    for(const key of version==='2c'?['username','security_level','has_auth_key','has_priv_key']:['has_community'])assert.equal(key in credential,false);
    return {payload,credential};
  }
  await page.getByRole('button',{name:'+ Credential',exact:true}).click();
  await page.getByLabel('Label',{exact:true}).fill('Browser polling');
  assert.equal(await page.getByLabel('Allowed source networks (optional)').inputValue(),'');
  assert.equal(await page.locator('[name=username],[name=security_level],[name=auth_key],[name=priv_key]').count(),0);
  await page.getByLabel('v2c community',{exact:true}).fill('browser-community');
  let result=await saveCredential('2c');
  assert.deepEqual(result.payload.networks,[]);assert.deepEqual(result.credential.networks,[]);assert.ok(result.credential.has_community);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByLabel('v2c community',{exact:true}).inputValue(),'');
  await page.getByLabel('Allowed source networks (optional)').fill('127.0.0.0/8, ::1/128');
  result=await saveCredential('2c');
  assert.equal('community' in result.payload,false);assert.ok(result.credential.has_community);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByLabel('Allowed source networks (optional)').inputValue(),'127.0.0.0/8, ::1/128');
  result=await saveCredential('2c');assert.deepEqual(result.credential.networks,['127.0.0.0/8','::1/128']);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('Allowed source networks (optional)').fill('');
  result=await saveCredential('2c');assert.deepEqual(result.credential.networks,[]);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('v2c community',{exact:true}).fill('discarded-unsaved-community');
  await page.getByLabel('SNMP version').selectOption('3');
  assert.equal(await page.locator('[name=community]').count(),0);
  assert.equal(await page.locator('[name=auth_key],[name=priv_key]').count(),0);
  await page.getByLabel('v3 username',{exact:true}).fill('browser-v3');
  await page.getByLabel('v3 security level').selectOption('authPriv');
  await page.getByLabel('SHA-256 passphrase',{exact:true}).fill('browser-auth-pass');
  await page.getByLabel('AES-128 passphrase',{exact:true}).fill('browser-priv-pass');
  result=await saveCredential('3');assert.ok(result.credential.has_auth_key&&result.credential.has_priv_key);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByLabel('SHA-256 passphrase',{exact:true}).inputValue(),'');
  assert.equal(await page.getByLabel('AES-128 passphrase',{exact:true}).inputValue(),'');
  result=await saveCredential('3');assert.equal('auth_key' in result.payload,false);assert.equal('priv_key' in result.payload,false);
  assert.ok(result.credential.has_auth_key&&result.credential.has_priv_key);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('SHA-256 passphrase',{exact:true}).fill('discarded-unsaved-auth');
  await page.getByLabel('SNMP version').selectOption('2c');
  assert.equal(await page.locator('[name=username],[name=security_level],[name=auth_key],[name=priv_key]').count(),0);
  assert.equal(await page.getByLabel('v2c community',{exact:true}).inputValue(),'');
  await page.getByLabel('v2c community',{exact:true}).fill('browser-replacement');
  result=await saveCredential('2c');assert.ok(result.credential.has_community);
  const final=await state();assert.equal(final.snmp.enabled,false);assert.equal(final.switch.identity.sys_object_id,null);
  await page.screenshot({path:path.join(screenshots,'settings.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('nav button[data-id=overview]').click();
  await page.screenshot({path:path.join(screenshots,'mobile.png'),fullPage:true});
  if(errors.length)throw new Error(errors.join('\n'));
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile page overflows viewport');
  console.log('Browser smoke passed: setup, pause, endpoint creation, attachment, learning, port edit, settings, mobile layout; no page errors.');
  await page.setViewportSize({width:1440,height:1100});
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('heading',{name:'Sign in',exact:true}).waitFor();
  assert.equal(await page.locator('[name=setup_token]').count(),0);
  assert.equal((await page.request.post(new URL('/api/v1/auth/setup',page.url()).href,{data:{password:'not-a-reset'}})).status(),409);
  await page.getByLabel('Administrator password').fill(process.env.SWITCHLAB_TEST_PASSWORD);
  await page.getByRole('button',{name:'Sign in'}).click();
  await page.getByRole('heading',{name:'Switch overview',exact:true}).waitFor();
  console.log('Credential browser checks passed: optional filters, version-only fields and payloads, blank-secret edits, protocol changes, short-password login and setup closure.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1);});

