// Run against a fresh local instance. Requires Playwright and Chromium.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browserEnv={...process.env};
  if(process.env.SWITCHLAB_BROWSER_LIBRARY_PATH)browserEnv.LD_LIBRARY_PATH=process.env.SWITCHLAB_BROWSER_LIBRARY_PATH;
  if(process.env.SWITCHLAB_BROWSER_FONTCONFIG)browserEnv.FONTCONFIG_FILE=process.env.SWITCHLAB_BROWSER_FONTCONFIG;
  const browser = await chromium.launch({headless:true,channel:process.env.SWITCHLAB_BROWSER_CHANNEL||undefined,env:browserEnv});
  try {
  const page = await browser.newPage({viewport:{width:1440,height:1100}});
  page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const screenshots=process.env.SWITCHLAB_TEST_SCREENSHOTS||path.join(__dirname,'../docs/screenshots');fs.mkdirSync(screenshots,{recursive:true});
  const fixtureURL=process.env.SWITCHLAB_TEST_URL||'http://127.0.0.1:8765';
  const fixtureOrigin=new URL(fixtureURL).origin;
  await page.route('**/*',route=>new URL(route.request().url()).origin===fixtureOrigin?route.continue():route.abort());
  await page.goto(fixtureURL);
  assert.equal(await page.locator('[name=setup_token]').count(),0);
  assert.equal(await page.getByLabel('Administrator password').getAttribute('minlength'),null);
  assert.equal(await page.getByLabel('Administrator password').getAttribute('maxlength'),'1024');
  await page.getByLabel('Administrator password').fill(process.env.SWITCHLAB_TEST_PASSWORD);
  await page.getByRole('button',{name:'Create administrator'}).click();
  await page.getByRole('heading',{name:'Switch overview',exact:true}).waitFor();
  await page.getByRole('button',{name:'Ⅱ Pause',exact:true}).click();
  await page.getByRole('button',{name:'▶ Resume',exact:true}).waitFor();
  await page.screenshot({path:path.join(screenshots,'overview-empty.png'),fullPage:true});
  await page.locator('nav button[data-id=endpoints]').click();
  await page.getByRole('button',{name:'+ New endpoint',exact:true}).click();
  await page.getByLabel('Display name').fill('Lab workstation');
  await page.getByLabel('MAC address',{exact:true}).fill('02:11:22:33:44:55');
  await page.getByRole('button',{name:'Create endpoint',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Attach →',exact:true}).click();
  await page.getByRole('button',{name:'Connect endpoint',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'+1s',exact:true}).click();
  await page.locator('nav button[data-id=fdb]').click();
  await page.getByText('02:11:22:33:44:55',{exact:true}).waitFor();
  await page.screenshot({path:path.join(screenshots,'learned-addresses.png'),fullPage:true});
  await page.locator('nav button[data-id=overview]').click();
  await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('show'));
  await page.screenshot({path:path.join(screenshots,'overview.png'),fullPage:true});
  await page.getByRole('button',{name:'Configure port',exact:true}).click();
  await page.getByLabel('Alias',{exact:true}).fill('Edited through the browser');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('nav button[data-id=settings]').click();
  const state=()=>page.evaluate(async()=> (await fetch('/api/v1/state')).json());
  const initialHost=(await state()).snmp.host;
  await page.getByRole('button',{name:'Configure',exact:true}).click();
  assert.equal(await page.getByRole('checkbox',{name:'Enable SNMP',exact:true}).count(),1);
  assert.equal(await page.getByRole('checkbox',{name:'Enable SNMP',exact:true}).isChecked(),false);
  assert.equal(await page.getByRole('checkbox',{name:'Explicitly enable SNMP',exact:true}).count(),0);
  await page.getByLabel('Listen IP address',{exact:true}).fill('127.0.0.2');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.reload();
  await page.locator('nav button[data-id=settings]').click();
  await page.getByRole('button',{name:'Configure',exact:true}).click();
  assert.equal(await page.getByLabel('Listen IP address',{exact:true}).inputValue(),'127.0.0.2');
  assert.equal(await page.getByRole('checkbox',{name:'Enable SNMP',exact:true}).isChecked(),false);
  assert.equal((await state()).switch.identity.sys_object_id,null);
  await page.getByLabel('Listen IP address',{exact:true}).fill(initialHost);
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  console.log('Listener form passed: exact Enable SNMP label, custom address roundtrip after reload, SNMP remains disabled.');
  const credentialRow=label=>page.locator('.setting-row').filter({has:page.locator('b',{hasText:label})});
  async function saveCredential(version){
    const request=page.waitForRequest(r=>r.url().includes('/api/v1/snmp/credentials')&&['POST','PUT'].includes(r.method()));
    await page.getByRole('button',{name:'Save changes',exact:true}).click();
    const payload=(await request).postDataJSON();
    await page.locator('dialog').waitFor({state:'hidden'});
    assert.equal(payload.version,version);
    const inactive=version==='2c'?['username','security_level','auth_key','priv_key']:['community'];
    for(const key of inactive)assert.equal(key in payload,false,`Inactive field ${key} submitted`);
    const snapshot=await state();
    const credential=Object.values(snapshot.credentials).find(c=>c.label===payload.label);
    assert.ok(credential);
    for(const key of ['community','auth_key','priv_key'])assert.equal(key in credential,false);
    for(const key of version==='2c'?['username','security_level','has_auth_key','has_priv_key']:['has_community'])assert.equal(key in credential,false);
    return {payload,credential};
  }
  await page.getByRole('button',{name:'+ Credential',exact:true}).click();
  await page.getByLabel('Label',{exact:true}).fill('Browser polling');
  assert.equal(await page.locator('[name=networks],[name=view_id],[name=purpose]').count(),0);
  assert.equal(await page.locator('[name=username],[name=security_level],[name=auth_key],[name=priv_key]').count(),0);
  await page.getByLabel('v2c community',{exact:true}).fill('browser-community');
  let result=await saveCredential('2c');
  assert.equal('polling' in result.payload,false);assert.deepEqual(result.credential.polling,{enabled:false,view_id:'all',networks:[]});assert.ok(result.credential.has_community);
  async function savePolling(label='Browser polling'){
    const request=page.waitForRequest(r=>r.url().includes('/api/v1/snmp/credentials')&&r.method()==='PUT');
    await page.getByRole('button',{name:'Save changes',exact:true}).click();
    const payload=(await request).postDataJSON();
    await page.locator('dialog').waitFor({state:'hidden'});
    assert.deepEqual(Object.keys(payload).sort(),['expected_configuration_revision','polling']);
    return Object.values((await state()).credentials).find(c=>c.label===label).polling;
  }
  await credentialRow('Browser polling').getByRole('button',{name:'Polling',exact:true}).click();
  assert.equal(await page.getByLabel('Allowed source networks (optional)').inputValue(),'');
  assert.equal(await page.locator('[name=community],[name=username],[name=auth_key],[name=priv_key]').count(),0);
  await page.getByLabel('Allow polling',{exact:true}).check();
  await page.getByLabel('Allowed source networks (optional)').fill('127.0.0.0/8, ::1/128');
  assert.deepEqual(await savePolling(),{enabled:true,view_id:'all',networks:['127.0.0.0/8','::1/128']});
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByLabel('v2c community',{exact:true}).inputValue(),'');
  result=await saveCredential('2c');assert.equal('community' in result.payload,false);assert.ok(result.credential.has_community);
  assert.deepEqual(result.credential.polling.networks,['127.0.0.0/8','::1/128']);
  await credentialRow('Browser polling').getByRole('button',{name:'Polling',exact:true}).click();
  assert.equal(await page.getByLabel('Allowed source networks (optional)').inputValue(),'127.0.0.0/8, ::1/128');
  await page.getByLabel('Allowed source networks (optional)').fill('');
  assert.deepEqual((await savePolling()).networks,[]);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('v2c community',{exact:true}).fill('discarded-unsaved-community');
  await page.getByLabel('SNMP version').selectOption('3');
  assert.equal(await page.locator('[name=community]').count(),0);
  assert.equal(await page.locator('[name=auth_key],[name=priv_key]').count(),0);
  await page.getByLabel('v3 username',{exact:true}).fill('browser-v3');
  await page.getByLabel('v3 security level').selectOption('authPriv');
  await page.getByLabel('SHA-256 passphrase',{exact:true}).fill('browser-auth-pass');
  await page.getByLabel('AES-128 passphrase',{exact:true}).fill('browser-priv-pass');
  result=await saveCredential('3');assert.ok(result.credential.has_auth_key&&result.credential.has_priv_key);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByLabel('SHA-256 passphrase',{exact:true}).inputValue(),'');
  assert.equal(await page.getByLabel('AES-128 passphrase',{exact:true}).inputValue(),'');
  result=await saveCredential('3');assert.equal('auth_key' in result.payload,false);assert.equal('priv_key' in result.payload,false);
  assert.ok(result.credential.has_auth_key&&result.credential.has_priv_key);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByLabel('SHA-256 passphrase',{exact:true}).fill('discarded-unsaved-auth');
  await page.getByLabel('SNMP version').selectOption('2c');
  assert.equal(await page.locator('[name=username],[name=security_level],[name=auth_key],[name=priv_key]').count(),0);
  assert.equal(await page.getByLabel('v2c community',{exact:true}).inputValue(),'');
  await page.getByLabel('v2c community',{exact:true}).fill('browser-replacement');
  result=await saveCredential('2c');assert.ok(result.credential.has_community);
  // Trap forms reuse credentials or create them atomically without incoming-access fields.
  const beforeTraps=await state();
  const sharedId=Object.values(beforeTraps.credentials).find(c=>c.label==='Browser polling').id;
  const noPollingFields=async()=>assert.equal(await page.locator('dialog [name=networks],dialog [name=view_id],dialog [name=purpose],dialog [name=polling]').count(),0);
  await page.getByRole('button',{name:'+ Target',exact:true}).click();
  await noPollingFields();
  await page.locator('dialog select[name=credential_mode]').selectOption('new');
  await page.getByLabel('Label',{exact:true}).fill('Canceled credential');
  await page.getByLabel('v2c community',{exact:true}).fill('canceled-secret');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  assert.deepEqual((await state()).credentials,beforeTraps.credentials);
  assert.deepEqual((await state()).targets,beforeTraps.targets);
  await page.getByRole('button',{name:'+ Target',exact:true}).click();
  await page.locator('dialog select[name=version]').selectOption('3');
  assert.equal(await page.locator('dialog select[name=credential_mode]').inputValue(),'new');
  await noPollingFields();
  assert.equal(await page.locator('[name=community]').count(),0);
  await page.getByLabel('Label',{exact:true}).fill('Inline browser v3');
  await page.getByLabel('v3 username',{exact:true}).fill('inline-browser-v3');
  await page.locator('dialog select[name=security_level]').selectOption('authPriv');
  await page.getByLabel('AES-128 passphrase',{exact:true}).fill('discarded-inline-privacy');
  await page.locator('dialog select[name=security_level]').selectOption('authNoPriv');
  assert.equal(await page.locator('[name=priv_key]').count(),0);
  await page.locator('dialog select[name=security_level]').selectOption('authPriv');
  assert.equal(await page.getByLabel('AES-128 passphrase',{exact:true}).inputValue(),'');
  await page.getByLabel('SHA-256 passphrase',{exact:true}).fill('inline-browser-auth');
  await page.getByLabel('AES-128 passphrase',{exact:true}).fill('inline-browser-priv');
  await page.getByLabel('Destination IP address',{exact:true}).fill('invalid-address');
  let response=page.waitForResponse(r=>r.url().endsWith('/api/v1/notifications/targets')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  assert.equal((await response).status(),422);
  await page.locator('.form-error').filter({hasText:'IP'}).waitFor();
  assert.deepEqual((await state()).credentials,beforeTraps.credentials);
  assert.deepEqual((await state()).targets,beforeTraps.targets);
  await page.getByLabel('Destination IP address',{exact:true}).fill('127.0.0.1');
  response=page.waitForResponse(r=>r.url().endsWith('/api/v1/notifications/targets')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  const createdResponse=await response;assert.equal(createdResponse.status(),200);
  const created=await createdResponse.json();
  const inlinePayload=createdResponse.request().postDataJSON();
  assert.equal('credential_id' in inlinePayload,false);
  assert.deepEqual(Object.keys(inlinePayload.new_credential).sort(),['auth_key','label','priv_key','security_level','username','version']);
  await page.locator('dialog').waitFor({state:'hidden'});
  let snapshot=await state();
  assert.equal(snapshot.targets[created.id].credential_id,created.credential_id);
  assert.deepEqual(snapshot.credentials[created.credential_id].polling,{enabled:false,view_id:'all',networks:[]});
  for(const key of ['community','auth_key','priv_key'])assert.equal(key in snapshot.credentials[created.credential_id],false);
  const targetRow=()=>page.locator('.setting-row').filter({has:page.locator('b',{hasText:'127.0.0.1:162'})});
  await targetRow().getByRole('button',{name:'Edit',exact:true}).click();
  await noPollingFields();
  assert.deepEqual(await page.locator('dialog select[name=credential_id]').locator('option').evaluateAll(o=>o.map(x=>x.value)),[created.credential_id]);
  assert.equal(await page.locator('[name=auth_key],[name=priv_key],[name=community]').count(),0);
  await page.locator('dialog select[name=version]').selectOption('2c');
  assert.deepEqual(await page.locator('dialog select[name=credential_id]').locator('option').evaluateAll(o=>o.map(x=>x.value)),[sharedId]);
  response=page.waitForResponse(r=>r.url().endsWith('/api/v1/notifications/targets/'+created.id)&&r.request().method()==='PUT');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  const selected=await response;assert.equal(selected.status(),200);
  assert.equal('new_credential' in selected.request().postDataJSON(),false);
  assert.equal(selected.request().postDataJSON().credential_id,sharedId);
  await page.locator('dialog').waitFor({state:'hidden'});
  snapshot=await state();assert.deepEqual(snapshot.credentials[sharedId].polling,beforeTraps.credentials[sharedId].polling);
  assert.ok(snapshot.credentials[created.credential_id]);
  await credentialRow('Browser polling').getByRole('button',{name:'Edit',exact:true}).click();
  await page.getByText('Trap destinations: 127.0.0.1:162.',{exact:false}).waitFor();
  assert.equal(await page.getByLabel('v2c community',{exact:true}).inputValue(),'');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await targetRow().getByRole('button',{name:'×',exact:true}).click();
  await page.getByRole('button',{name:'Delete record',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  snapshot=await state();assert.equal(Object.keys(snapshot.targets).length,0);assert.equal(Object.keys(snapshot.credentials).length,2);
  console.log('Shared trap browser checks passed: inline create/cancel/failure atomicity, version filtering, secret-free selection, polling separation and retained credentials.');
  // Inactive polling retains missing views without blocking trap credentials.
  await credentialRow('Browser polling').getByRole('button',{name:'Polling',exact:true}).click();
  await page.getByLabel('Allow polling',{exact:true}).uncheck();
  assert.equal((await savePolling()).enabled,false);
  for(const view of Object.values((await state()).views)){
    await page.locator(`button[data-action="delete-view"][data-id="${view.id}"]`).click();
    await page.getByRole('button',{name:'Delete record',exact:true}).click();
    await page.locator('dialog').waitFor({state:'hidden'});
  }
  assert.deepEqual((await state()).views,{});
  const literalLabel='Browser <span data-fixture="polling-label">literal</span> & view';
  await page.getByRole('button',{name:'+ Target',exact:true}).click();
  await noPollingFields();
  await page.locator('dialog select[name=credential_mode]').selectOption('new');
  await page.getByLabel('Label',{exact:true}).fill(literalLabel);
  await page.getByLabel('v2c community',{exact:true}).fill('browser-no-read-view');
  response=page.waitForResponse(r=>r.url().endsWith('/api/v1/notifications/targets')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  const noViewResponse=await response;assert.equal(noViewResponse.status(),200);
  const noView=await noViewResponse.json();
  await page.locator('dialog').waitFor({state:'hidden'});
  const retainedTarget=(await state()).targets[noView.id];
  const openLiteralPolling=async()=>{
    await credentialRow(literalLabel).getByRole('button',{name:'Polling',exact:true}).click();
    assert.equal(await page.locator('dialog h2').textContent(),'Polling access · '+literalLabel);
    assert.equal(await page.locator('dialog h2 *').count(),0);
    assert.equal(await page.locator('[data-fixture="polling-label"]').count(),0);
  };
  await openLiteralPolling();
  assert.equal(await page.locator('dialog select[name=view_id]').inputValue(),'all');
  assert.equal(await page.locator('dialog select[name=view_id] option:checked').textContent(),'Missing view · all');
  await page.getByLabel('Allowed source networks (optional)').fill('127.0.0.0/8');
  assert.deepEqual(await savePolling(literalLabel),{enabled:false,view_id:'all',networks:['127.0.0.0/8']});
  await page.getByRole('button',{name:'+ View',exact:true}).click();
  await page.getByLabel('Name',{exact:true}).fill('Replacement read view');
  response=page.waitForResponse(r=>r.url().endsWith('/api/v1/snmp/views')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  const viewResponse=await response;assert.equal(viewResponse.status(),200);
  const viewId=(await viewResponse.json()).id;
  await page.locator('dialog').waitFor({state:'hidden'});
  await openLiteralPolling();
  assert.equal(await page.locator('dialog select[name=view_id]').inputValue(),'all');
  assert.equal(await page.locator('dialog select[name=view_id] option:checked').textContent(),'Missing view · all');
  assert.deepEqual(await page.locator('dialog select[name=view_id] option').evaluateAll(options=>options.map(o=>o.value)),['all',viewId]);
  const beforeMissing=await state();
  await page.getByLabel('Allow polling',{exact:true}).check();
  response=page.waitForResponse(r=>r.url().endsWith('/api/v1/snmp/credentials/'+noView.credential_id)&&r.request().method()==='PUT');
  await page.getByRole('button',{name:'Save changes',exact:true}).click();
  assert.equal((await response).status(),422);
  await page.locator('.form-error').filter({hasText:'Unknown read view'}).waitFor();
  snapshot=await state();assert.equal(snapshot.configuration_revision,beforeMissing.configuration_revision);
  assert.deepEqual(snapshot.credentials,beforeMissing.credentials);assert.deepEqual(snapshot.targets,beforeMissing.targets);
  await page.locator('dialog select[name=view_id]').selectOption(viewId);
  assert.deepEqual(await savePolling(literalLabel),{enabled:true,view_id:viewId,networks:['127.0.0.0/8']});
  await openLiteralPolling();
  await page.getByLabel('Allow polling',{exact:true}).uncheck();
  assert.deepEqual(await savePolling(literalLabel),{enabled:false,view_id:viewId,networks:['127.0.0.0/8']});
  await page.locator(`button[data-action="delete-view"][data-id="${viewId}"]`).click();
  await page.getByRole('button',{name:'Delete record',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  snapshot=await state();assert.deepEqual(snapshot.views,{});
  assert.deepEqual(snapshot.targets[noView.id],retainedTarget);assert.ok(snapshot.credentials[noView.credential_id].enabled);
  assert.deepEqual(snapshot.credentials[noView.credential_id].polling,{enabled:false,view_id:viewId,networks:['127.0.0.0/8']});
  console.log('Polling corrections passed: literal HTML-like heading, no injected element, no-view inline trap creation, explicit missing selection, atomic rejection, valid-view enablement and retained inactive fields/target.');
  const final=await state();assert.equal(final.snmp.enabled,false);assert.equal(final.switch.identity.sys_object_id,null);
  await page.screenshot({path:path.join(screenshots,'settings.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('nav button[data-id=overview]').click();
  await page.screenshot({path:path.join(screenshots,'mobile.png'),fullPage:true});
  if(errors.length)throw new Error(errors.join('\n'));
  if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('Mobile page overflows viewport');
  console.log('Browser smoke passed: setup, pause, endpoint creation, attachment, learning, port edit, settings, mobile layout; no page errors.');
  await page.setViewportSize({width:1440,height:1100});
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.getByRole('heading',{name:'Sign in',exact:true}).waitFor();
  assert.equal(await page.locator('[name=setup_token]').count(),0);
  assert.equal((await page.request.post(new URL('/api/v1/auth/setup',page.url()).href,{data:{password:'not-a-reset'}})).status(),409);
  await page.getByLabel('Administrator password').fill(process.env.SWITCHLAB_TEST_PASSWORD);
  await page.getByRole('button',{name:'Sign in'}).click();
  await page.getByRole('heading',{name:'Switch overview',exact:true}).waitFor();
  console.log('Credential browser checks passed: optional filters, version-only fields and payloads, blank-secret edits, protocol changes, short-password login and setup closure.');
  } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exit(1);});

